### ISSUE TITLE
template functionality not available

### ISSUE THREAD

**Issue by skasberger** [openknowledge-archive/wordpress-theme-with-bp#38] opened 2016-11-26 14:38 UTC
The function to choose a template for a page at the backend is not available since the update (okfn.at).
![back](https://cloud.githubusercontent.com/assets/1374253/20640998/3f4bcafc-b3ee-11e6-8acc-9ff850e6574c.png)

so it is not possible anymore to use a fullside template, and every page is rendered with a sidebar.
![front](https://cloud.githubusercontent.com/assets/1374253/20640999/3f4c0f8a-b3ee-11e6-9698-9baa7d89af79.png)

**Comment by pwalsh** [comment] 2016-11-30 06:25
@gocemitevski and @morchickit can you please sync to get this sorted asap.

**Comment by gocemitevski** [comment] 2016-11-30 11:38
@skasberger I don't remember doing any changes to the page templates functionality, so this is definitely a bug. Doing checks to find the cause.

cc @pwalsh

**Comment by gocemitevski** [comment] 2016-12-05 14:56
We do not provide any custom page templates with the new OKI theme and that's why the functionality is not available. WordPress scans for any custom page templates and removes the dropdown if none are discovered.

Any custom templates which need to be provided, need to be added additionally.

@skasberger aside from the Full-width template, what other templates do you need?

cc @pwalsh

**Comment by pwalsh** [comment] 2016-12-05 16:03
@gocemitevski sync with @morchickit on this please.

**Comment by skasberger** [comment] 2016-12-05 16:25
thats all for me. full width and one with sidebar (which is the default page).

**Comment by gocemitevski** [comment] 2016-12-06 09:22
@skasberger a Full Width page template should now be available on your website and basically, all websites in the OKI network which use this theme.

cc @morchickit @pwalsh

**Comment by gocemitevski** [comment] 2016-12-12 12:18
@pwalsh @morchickit can we close this?

**Closed as completed** 2016-12-12 12:23 UTC
Labels: bug
